#!/usr/bin/env ruby
require 'lib/host'
require 'lib/hosts'
require 'lib/lock'
require 'lib/remote_file'
require 'lib/suites'
require 'lib/configuration'

$config = Configuration.new do |config|
  config.remote_path = "~/workspace/remote/#{$hostname}"
  config.local_path = Dir.getwd
  config.hosts = ["elizabeth", "bedford"]
  config.suites = [
    "source ~/.profile; rvm use ree-1.8.7-2010.02@casebook; bundle install; bundle exec spec spec/models/api/",
    "source ~/.profile; rvm use ree-1.8.7-2010.02@casebook; bundle install; bundle exec spec spec/models/date_strategy/"
  ]
end
$config.run

